const suits=[{name:"hearts",start:1},{name:"spades",start:15},{name:"diamonds",start:29},{name:"clubs",start:43}],ranks=["A","2","3","4","5","6","7","8","9","10","J","Q","K"],scores={"High Card":0,"One Pair":2,"Two Pair":5,"Three of a Kind":10,Straight:15,Flush:20,"Full House":25,"Four of a Kind":50,"Straight Flush":75,"Royal Flush":100},$=s=>document.querySelector(s);
const board=$("#board"),rowHands=$("#row-hands"),columnHands=$("#column-hands"),status=$("#status"),deckButton=$("#deck"),currentCardElement=$("#current-card");
let grid,deck,currentCard,selected,swaps,phase,saved;
const pad=n=>String(n).padStart(2,"0");
function createDeck(){return suits.flatMap(s=>ranks.map((rank,i)=>({rank,rankValue:i+1,suit:s.name,image:`img/card assets/${pad(s.start+i)}_kerenel_Cards.png`})))}
function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function evaluate(cards){if(cards.some(c=>!c))return{name:"Incomplete",score:0};const map=new Map;cards.forEach(c=>map.set(c.rankValue,(map.get(c.rankValue)||0)+1));const counts=[...map.values()].sort((a,b)=>b-a),v=[...map.keys()].sort((a,b)=>a-b),flush=cards.every(c=>c.suit===cards[0].suit),wheel=v.join()==="1,2,3,4,5",royal=v.join()==="1,10,11,12,13",straight=wheel||royal||(v.length===5&&v[4]-v[0]===4);let name="High Card";if(royal&&flush)name="Royal Flush";else if(straight&&flush)name="Straight Flush";else if(counts[0]===4)name="Four of a Kind";else if(counts[0]===3&&counts[1]===2)name="Full House";else if(flush)name="Flush";else if(straight)name="Straight";else if(counts[0]===3)name="Three of a Kind";else if(counts[0]===2&&counts[1]===2)name="Two Pair";else if(counts[0]===2)name="One Pair";return{name,score:scores[name]}}
function hands(){return{rows:Array.from({length:5},(_,r)=>evaluate(grid.slice(r*5,r*5+5))),columns:Array.from({length:5},(_,c)=>evaluate(Array.from({length:5},(_,r)=>grid[r*5+c])))}}
function total(){const h=hands();return[...h.rows,...h.columns].reduce((sum,x)=>sum+x.score,0)}
function handHTML(h,label){return`<div class="hand${h.score?" scoring":""}" aria-label="${label}: ${h.name}"><span>${h.score?`${h.name} <b>+${h.score}</b>`:""}</span></div>`}
function render(){const h=hands(),hot=new Set;h.rows.forEach((x,r)=>{if(x.score)for(let c=0;c<5;c++)hot.add(r*5+c)});h.columns.forEach((x,c)=>{if(x.score)for(let r=0;r<5;r++)hot.add(r*5+c)});board.innerHTML=grid.map((card,i)=>card?`<button class="card${selected===i?" selected":""}${hot.has(i)?" scoring":""}" data-i="${i}" ${phase==="placing"?"disabled":""} aria-label="${card.rank} of ${card.suit}"><img src="${card.image}" alt=""></button>`:`<button class="card empty" data-i="${i}" ${currentCard?"":"disabled"} aria-label="Empty square"></button>`).join("");rowHands.innerHTML=h.rows.map((x,i)=>handHTML(x,`Row ${i+1}`)).join("");columnHands.innerHTML=h.columns.map((x,i)=>handHTML(x,`Column ${i+1}`)).join("");$("#score").textContent=total();$("#swaps").textContent=swaps;$("#deck-count").textContent=deck.length;deckButton.disabled=phase!=="placing"||!!currentCard;currentCardElement.innerHTML=currentCard?`<img src="${currentCard.image}" alt="${currentCard.rank} of ${currentCard.suit}">`:""}
function deal(){if(deckButton.disabled)return;currentCard=deck.pop();status.textContent=`Place the ${currentCard.rank} of ${currentCard.suit} in an empty square.`;render()}
function place(i){if(!currentCard||grid[i])return;grid[i]=currentCard;currentCard=null;const n=grid.filter(Boolean).length;if(n===25){phase="swapping";status.textContent="All cards placed. Select two cards to swap."}else status.textContent=`${25-n} spaces left. Deal the next card.`;render()}
function saveScore(){if(saved)return;saved=true;const list=JSON.parse(localStorage.getItem("pokerSquaresScores")||"[]");list.push({score:total(),date:new Date().toISOString()});list.sort((a,b)=>b.score-a.score);localStorage.setItem("pokerSquaresScores",JSON.stringify(list.slice(0,5)));renderLeaderboard()}
function choose(i){if(phase==="placing")return place(i);if(!swaps)return;if(selected===null){selected=i;status.textContent=`${grid[i].rank} of ${grid[i].suit} selected. Choose another card.`}else if(selected===i){selected=null;status.textContent="Selection cleared."}else{[grid[selected],grid[i]]=[grid[i],grid[selected]];selected=null;swaps--;status.textContent=swaps?`${swaps} swaps left.`:`Round complete. Final score: ${total()}.`;if(!swaps)saveScore()}render()}
function renderLeaderboard(){const list=JSON.parse(localStorage.getItem("pokerSquaresScores")||"[]");$("#leaderboard").innerHTML=list.length?list.map(x=>`<li><span>${new Date(x.date).toLocaleDateString(undefined,{month:"short",day:"numeric"})}</span><strong>${x.score} pts</strong></li>`).join(""):`<li><span>Finish a round to set your first score.</span></li>`}
function newRound(){if(phase==="swapping"&&!saved)saveScore();grid=Array(25).fill(null);deck=shuffle(createDeck());currentCard=null;selected=null;swaps=3;phase="placing";saved=false;status.textContent="Click the deck to deal your first card.";render()}
board.addEventListener("click",e=>{const card=e.target.closest(".card");if(card)choose(Number(card.dataset.i))});deckButton.addEventListener("click",deal);$("#new-round").addEventListener("click",newRound);$("#rules-open").addEventListener("click",()=>$("#rules").showModal());$("#rules-close").addEventListener("click",()=>$("#rules").close());$("#rules").addEventListener("click",e=>{if(e.target===$("#rules"))e.target.close()});$("#scoring").innerHTML=Object.entries(scores).reverse().map(([h,p])=>`<span>${h}</span><span>${p}</span>`).join("");renderLeaderboard();newRound();
